// Code generated by schema-generate. DO NOT EDIT.

package main

// Address Address
type Address struct {

	// County
	County string `json:"county,omitempty"`

	// Address 2
	District string `json:"district,omitempty"`

	// Flat
	FlatNumber string `json:"flatNumber,omitempty"`

	// House Name
	HouseName string `json:"houseName,omitempty"`

	// House Number
	HouseNumber string `json:"houseNumber,omitempty"`

	// Postcode
	Postcode string `json:"postcode,omitempty"`

	// Address 1
	Street string `json:"street,omitempty"`

	// City
	Town string `json:"town,omitempty"`
}

// Example example
type Example struct {
	Address *Address `json:"address,omitempty"`
	Name    string   `json:"name,omitempty"`
	Status  *Status  `json:"status,omitempty"`
}

// Status
type Status struct {

	// The favourite cat.
	Favouritecat string `json:"favouritecat,omitempty"`
}
